// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: message.proto
#ifndef GRPC_message_2eproto__INCLUDED
#define GRPC_message_2eproto__INCLUDED

#include "message.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace kilovictor {

class KiloVictor final {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status getNumeric(::grpc::ClientContext* context, const ::kilovictor::Key& request, ::kilovictor::NumericValue* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kilovictor::NumericValue>> AsyncgetNumeric(::grpc::ClientContext* context, const ::kilovictor::Key& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kilovictor::NumericValue>>(AsyncgetNumericRaw(context, request, cq));
    }
    virtual ::grpc::Status setNumeric(::grpc::ClientContext* context, const ::kilovictor::NumericKeyValue& request, ::kilovictor::NumericValue* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kilovictor::NumericValue>> AsyncsetNumeric(::grpc::ClientContext* context, const ::kilovictor::NumericKeyValue& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kilovictor::NumericValue>>(AsyncsetNumericRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::kilovictor::NumericValue>* AsyncgetNumericRaw(::grpc::ClientContext* context, const ::kilovictor::Key& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::kilovictor::NumericValue>* AsyncsetNumericRaw(::grpc::ClientContext* context, const ::kilovictor::NumericKeyValue& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status getNumeric(::grpc::ClientContext* context, const ::kilovictor::Key& request, ::kilovictor::NumericValue* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kilovictor::NumericValue>> AsyncgetNumeric(::grpc::ClientContext* context, const ::kilovictor::Key& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kilovictor::NumericValue>>(AsyncgetNumericRaw(context, request, cq));
    }
    ::grpc::Status setNumeric(::grpc::ClientContext* context, const ::kilovictor::NumericKeyValue& request, ::kilovictor::NumericValue* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kilovictor::NumericValue>> AsyncsetNumeric(::grpc::ClientContext* context, const ::kilovictor::NumericKeyValue& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kilovictor::NumericValue>>(AsyncsetNumericRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::kilovictor::NumericValue>* AsyncgetNumericRaw(::grpc::ClientContext* context, const ::kilovictor::Key& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::kilovictor::NumericValue>* AsyncsetNumericRaw(::grpc::ClientContext* context, const ::kilovictor::NumericKeyValue& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::RpcMethod rpcmethod_getNumeric_;
    const ::grpc::RpcMethod rpcmethod_setNumeric_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status getNumeric(::grpc::ServerContext* context, const ::kilovictor::Key* request, ::kilovictor::NumericValue* response);
    virtual ::grpc::Status setNumeric(::grpc::ServerContext* context, const ::kilovictor::NumericKeyValue* request, ::kilovictor::NumericValue* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_getNumeric : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_getNumeric() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_getNumeric() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getNumeric(::grpc::ServerContext* context, const ::kilovictor::Key* request, ::kilovictor::NumericValue* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetNumeric(::grpc::ServerContext* context, ::kilovictor::Key* request, ::grpc::ServerAsyncResponseWriter< ::kilovictor::NumericValue>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_setNumeric : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_setNumeric() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_setNumeric() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setNumeric(::grpc::ServerContext* context, const ::kilovictor::NumericKeyValue* request, ::kilovictor::NumericValue* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsetNumeric(::grpc::ServerContext* context, ::kilovictor::NumericKeyValue* request, ::grpc::ServerAsyncResponseWriter< ::kilovictor::NumericValue>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_getNumeric<WithAsyncMethod_setNumeric<Service > > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_getNumeric : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_getNumeric() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_getNumeric() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getNumeric(::grpc::ServerContext* context, const ::kilovictor::Key* request, ::kilovictor::NumericValue* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_setNumeric : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_setNumeric() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_setNumeric() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setNumeric(::grpc::ServerContext* context, const ::kilovictor::NumericKeyValue* request, ::kilovictor::NumericValue* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_getNumeric : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_getNumeric() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::StreamedUnaryHandler< ::kilovictor::Key, ::kilovictor::NumericValue>(std::bind(&WithStreamedUnaryMethod_getNumeric<BaseClass>::StreamedgetNumeric, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_getNumeric() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status getNumeric(::grpc::ServerContext* context, const ::kilovictor::Key* request, ::kilovictor::NumericValue* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedgetNumeric(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::kilovictor::Key,::kilovictor::NumericValue>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_setNumeric : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_setNumeric() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::StreamedUnaryHandler< ::kilovictor::NumericKeyValue, ::kilovictor::NumericValue>(std::bind(&WithStreamedUnaryMethod_setNumeric<BaseClass>::StreamedsetNumeric, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_setNumeric() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status setNumeric(::grpc::ServerContext* context, const ::kilovictor::NumericKeyValue* request, ::kilovictor::NumericValue* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedsetNumeric(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::kilovictor::NumericKeyValue,::kilovictor::NumericValue>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_getNumeric<WithStreamedUnaryMethod_setNumeric<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_getNumeric<WithStreamedUnaryMethod_setNumeric<Service > > StreamedService;
};

}  // namespace kilovictor


#endif  // GRPC_message_2eproto__INCLUDED
